CREATE TABLE DOCUMENTS(
    ID uuid DEFAULT uuid_generate_v4(),
    FILE_NAME VARCHAR(200) NOT NULL,
    PROCESS_STATUS VARCHAR(20) NOT NULL,
    PROCESS_DESCRIPTION VARCHAR(150),
    COLLECTION_NAME VARCHAR,
    CONSTRAINT documents_pkey PRIMARY KEY (ID)
);