CREATE TABLE DOCUMENTS(
    ID uuid DEFAULT uuid_generate_v4(),
    FILE_NAME VARCHAR(200) NOT NULL,
    NAME_HASH VARCHAR(256) NOT NULL,
    CONTENT_HASH VARCHAR(512) NOT NULL,
    PROCESS_STATUS VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(100),
    COLLECTION_ID uuid,
    PRIMARY KEY (ID)
);