name: Check code style

on: [push, pull_request]

jobs:
  analyse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Check formatting with Black
      uses: psf/black@stable
      with:
        options: "--check --diff"
        src: "./oairag"
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=5 $(git ls-files '*.py')
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2023.2
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
