name: Analyse static code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with Black
      uses: psf/black@stable
      with:
        options: "--check --diff"
        src: "./oairag"
  qodana:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2023.2
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
